---

- include: asserts.yml


- block:

    - include_vars: vars/users/{{ ipa_varlist }}.yml

    - include: user.yml
      with_items: '{{ ipa_users }}'

  when: ipa_mode == 'users' or ipa_mode == 'newuser'


- block:

    - include_vars: vars/zones/{{ ipa_varlist }}.yml

    - include: dnszone.yml

  when: ipa_mode == 'dns'


- block:

    - name: get vars
      find:
        paths: '{{ role_path }}/vars/groups'
        file_type: file
      register: get_vars

    - include: group.yml
      with_items: "{{ get_vars.files | map (attribute='path') | list }}"

  when: ipa_mode == 'groups' or ipa_mode == 'newuser'


- block:

    - name: get vars
      find:
        paths: '{{ role_path }}/vars/hbac'
        file_type: file
      register: get_vars

    - include: hbacrule.yml
      with_items: "{{ get_vars.files | map (attribute='path') | list }}"

  when: ipa_mode == 'hbac' or ipa_mode == 'policy' or ipa_mode == 'newuser'


- block:

    - name: get vars
      find:
        paths: '{{ role_path }}/vars/sudo'
        file_type: file
      register: get_vars

    - include: sudorule.yml
      with_items: "{{ get_vars.files | map (attribute='path') | list }}"

  when: ipa_mode == 'sudo' or ipa_mode == 'policy' or ipa_mode == 'newuser'
